Repository atownse/rancid-tomatillos, pull requests merged in 2020-12, with the labels that each got.

#13 Feature/fetch requests
  src/App/App.js
  src/Card/Card.js
  src/SingleMovie/SingleMovie.js
  src/apiCalls.js
Labels: feature, refactor

#16 Refactor/router
  src/App/App.js
  src/Card/Card.js
  src/Movies/Movies.js
  src/SingleMovie/SingleMovie.js
  src/index.js
Labels: refactor

#17 Testing/router
  src/App/App.js
  src/App/App.test.js
  src/Card/Card.test.js
  src/Movies/Movies.js
  src/Movies/Movies.test.js
  src/SingleMovie/SingleMovie.js
  src/SingleMovie/SingleMovie.test.js
Labels: testing

#20 Add tests to all testing files
  src/App/App.js
  src/App/App.test.js
  src/Card/Card.test.js
  src/Movies/Movies.test.js
  src/SingleMovie/SingleMovie.test.js
Labels: refactor, testing

#24 Feature/search movies
  src/App/App.test.js
  src/Movies/Movies.css
  src/Movies/Movies.js
  src/Movies/Movies.test.js
Labels: feature, testing

#25 Refactor search functioanlity & debug
  src/App/App.js
  src/Movies/Movies.css
  src/Movies/Movies.js
  src/SingleMovie/SingleMovie.test.js
Labels: refactor
